GET http://localhost:3000/movies/

###

POST http://localhost:3000/movies/
Content-Type: application/json

{
    "title": "test",
    "description": "test",
    "id": 3,
    "price": null
}

###

DELETE http://localhost:3000/movies/

###

PUT http://localhost:3000/movies/1
Content-Type: application/json

{
    "title": "Zlatans Historia",
    "description": "hur Zlatan blev den han blev",
    "price": 1000
}
