GET http://localhost:3000/movies/

###

POST http://localhost:3000/movies/
Content-Type: application/json

{
    "title": "banan",
    "description": "red man in tight leggings tell jokes",
    "id": 2,
    "price": 49
}

###

DELETE http://localhost:3000/movies/

###

PUT http://localhost:3000/movies/1
Content-Type: application/json

{
    "title": "Zlatans Historia",
    "description": "hur Zlatan blev den han blev",
    "price": 1000
}
